import './MagicPodFastfile'

default_platform(:ios)

platform :ios do
  BUILD_CONFIGS = {
    "release" => {
      provisioning_profile_specifier: "match AppStore com.yusuga.App"
    }
  }
  
  before_all do
    setup_circle_ci
  end
  
  desc "Build"
  lane :build do |options|
    config = BUILD_CONFIGS[options[:configuration]]
    
    # @see https://docs.fastlane.tools/actions/match/
    match(
      type: 'appstore',
      git_url: 'git@github.com:yusuga/certificates.git',
      app_identifier: "com.yusuga.App",
      readonly: true
    )
    
    # @see https://docs.fastlane.tools/actions/update_code_signing_settings/
    update_code_signing_settings(
      path: "App/App.xcodeproj",
      use_automatic_signing: false, 
      code_sign_identity: "iPhone Distribution",
      profile_name: config[:provisioning_profile_specifier],
    )
    
    # @see https://docs.fastlane.tools/actions/gym/
    gym(
      workspace: "App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      codesigning_identity: "Apple Distribution: Yu Sugawara (R7YY29B6T8)",
      clean: true,
      disable_xcpretty: true
    )
  end
  
  lane :build_for_simulator do |options|
    gym(
      workspace: "App/App.xcworkspace",
      scheme: "App",
      configuration: "Development",
      sdk: "iphonesimulator",
      destination: "generic/platform=iOS Simulator",
      derived_data_path: options[:derived_data_path],
      skip_package_ipa: true,
      skip_archive: true,
      clean: true,
      disable_xcpretty: true
    )
  end
end
